# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('pumba', models.CommaSeparatedIntegerField(max_length=100)),
            ],
        ),
    ]
